name: Deploy dev

on:
  push:
    branches:
      - dev

permissions:
  contents: read

jobs:
  deploy:
    uses: ./.github/workflows/cloudflare-pages.yaml
    secrets: inherit
    with:
      build_env: dev
      cloudflare_branch: dev
